### ISSUE TITLE
OpenSearch cluster/domain provisioning support

### ISSUE THREAD

**Issue by achitojha** [opensearch-project/opensearch-benchmark#100]
Build support to provision Amazon OpenSearch Service domains. This should be built as a plugin allowing users to selectively use plugins of their choice.

**Comment by gkamat** [comment]
Since OSB is an open-source project, provisioning clusters based off a specific cloud provider would not be part of its charter.  This could be implemented via a generic plugin-type mechanism that could be applied to various services, and would be tackled as a separate issue.
