### ISSUE TITLE
[META] Improve documentation for OpenSearch-Benchmark

### ISSUE THREAD

**Issue by achitojha** [opensearch-project/opensearch-benchmark#101]
Create documentation for OpenSearch Benchmark. This should help users understand various nuances inside OpenSearch Benchmark

**Comment by LuluNwenyi** [comment]
Hello, @achitojha I would love to get my hands on this. However, I'd like to know more about this project so I can understand what needs to be documented.

**Comment by achitojha** [comment]
Hi @LuluNwenyi 

Thanks for showing interest in contributing to this project. We're working towards coming up with more concrete and smaller scope issues which could be completed with a few PRs. This issue will be tracking all the work across all of the issues. We will put out these when we're ready and you can start contributing.

Here's some resources you can use to get familiar with OpenSearch Benchmark : 
- [Developer Guide](https://github.com/opensearch-project/opensearch-benchmark/blob/main/DEVELOPER_GUIDE.md)
- [Readme document](https://github.com/opensearch-project/opensearch-benchmark/blob/main/README.md)

**Comment by sharp-pixel** [comment]
Any update on this issue?

**Comment by bbarani** [comment]
Overall documentation including [developer guide](https://github.com/opensearch-project/opensearch-benchmark/blob/main/DEVELOPER_GUIDE.md) and [readme.md](https://github.com/opensearch-project/opensearch-benchmark/blob/main/README.md) needs to be updated to reflect the current status. We will be working on updating these gaps soon.

**Comment by gkamat** [comment]
First release of the documentation is [now online](https://opensearch.org/docs/2.7/benchmark/index/).  This will continue to be updated and enhanced going forward.

**Comment by IanHoang** [comment]
Documentation enhancements are being tracked in this META issue now: https://github.com/opensearch-project/opensearch-benchmark/issues/611
