### ISSUE TITLE
Cannot run task [index-append] with http_logs workload

### ISSUE THREAD

**Issue by LuigiCerone** [opensearch-project/opensearch-benchmark#105]
When I try to run benchmarks using `http_logs` workload, I get an error on `index_append` task execution.

**To Reproduce**
I'm using a dockerized environment (specifically the [official docker-compose example](https://opensearch.org/docs/latest/opensearch/install/docker/#sample-docker-compose-file)).
```bash
docker-compose up -d 
```
Then I add to the network a container with Python and I install this library:

```bash
docker run -it --entrypoint bash --network=opensearch_opensearch-net python:3.8

# Inside Python container:
root@80f98d9b4de2:/# pip3 install opensearch-benchmark
root@80f98d9b4de2:/# opensearch-benchmark execute_test --workload=http_logs --target-hosts=opensearch-node1:9200,opensearch-node2:9200 --pipeline=benchmark-only --client-options="use_ssl:true,verify_certs:false,basic_auth_user:'admin',basic_auth_password:'admin'"
```

**Expected behavior**
Get a clean execution with benchmarking results from this specific type of data.

**Logs**
```
root@80f98d9b4de2:/# opensearch-benchmark execute_test --workload=http_logs --target-hosts=opensearch-node1:9200,opensearch-node2:9200 --pipeline=benchmark-only --client-options="use_ssl:true,verify_certs:false,basic_auth_user:'admin',basic_auth_password:'admin'"

   ____                  _____                      __       ____                  __                         __
  / __ \____  ___  ____ / ___/___  ____ ___________/ /_     / __ )___  ____  _____/ /_  ____ ___  ____ ______/ /__
 / / / / __ \/ _ \/ __ \\__ \/ _ \/ __ `/ ___/ ___/ __ \   / __  / _ \/ __ \/ ___/ __ \/ __ `__ \/ __ `/ ___/ //_/
/ /_/ / /_/ /  __/ / / /__/ /  __/ /_/ / /  / /__/ / / /  / /_/ /  __/ / / / /__/ / / / / / / / / /_/ / /  / ,<
\____/ .___/\___/_/ /_/____/\___/\__,_/_/   \___/_/ /_/  /_____/\___/_/ /_/\___/_/ /_/_/ /_/ /_/\__,_/_/  /_/|_|
    /_/

[INFO] You did not provide an explicit timeout in the client options. Assuming default of 10 seconds.
[INFO] Executing test with workload [http_logs], test_procedure [append-no-conflicts] and provision_config_instance ['external'] with version [1.2.3].

[WARNING] merges_total_time is 105643 ms indicating that the cluster is not in a defined clean state. Recorded index time metrics may be misleading.
[WARNING] merges_total_throttled_time is 2889 ms indicating that the cluster is not in a defined clean state. Recorded index time metrics may be misleading.
[WARNING] indexing_total_time is 1096703 ms indicating that the cluster is not in a defined clean state. Recorded index time metrics may be misleading.
[WARNING] refresh_total_time is 117937 ms indicating that the cluster is not in a defined clean state. Recorded index time metrics may be misleading.
[WARNING] flush_total_time is 135 ms indicating that the cluster is not in a defined clean state. Recorded index time metrics may be misleading.
Running delete-index                                                           [100% done]
Running create-index                                                           [100% done]
Running check-cluster-health                                                   [100% done]
Running index-append                                                           [  0% done]



[ERROR] Cannot execute_test. Error in load generator [0]
	Cannot run task [index-append]: expected str, bytes or os.PathLike object, not NoneType

Getting further help:
*********************
* Check the log files in /root/.benchmark/logs for errors.
* Read the documentation at https://opensearch.org/docs.
* Ask a question on the forum at https://discuss.opendistrocommunity.dev/.
* Raise an issue at https://github.com/opensearch-project/OpenSearch-Benchmark/issues and include the log files in /root/.benchmark/logs.

--------------------------------
[INFO] FAILURE (took 32 seconds)
--------------------------------
````

[Here](https://github.com/opensearch-project/opensearch-benchmark/files/7898013/benchmark.log) you can find also the log file `/root/.benchmark/logs/benchmark.log`.

**More Context:**

Versions:
* python:3.8
* opensearchproject/opensearch-dashboards:1.2.0
* opensearchproject/opensearch:1.2.3
* opensearch-benchmark   0.0.1

**Additional context**

If I use different workloads, benchmarking is working fine.  I've only tried with `geonames` and `percolator`(but this last one seems to not have a index-append task).

**Comment by IanHoang** [comment]
Hi @LuigiCerone, we are currently looking into this. Could you please provide more information about the domain's configuration to better help us reproduce this issue?

**Comment by LuigiCerone** [comment]
Hello @IanHoang thanks for your reply.

As I said in the original comment, I'm using a dockerized environment which I bring up using the [official docker-compose example](https://opensearch.org/docs/latest/opensearch/install/docker/#sample-docker-compose-file). Specifically I've:

* Docker version 20.10.6, build 370c289
* docker-compose version 1.29.1, build c34c88b2


IDK if this could help, but I'm on Mac OS Monterey, version: 12.0.1 (21A559).

**Comment by Rishikesh1159** [comment]
I faced similar error on index_append task execution when I try to run opensearch-benchmark on http_logs workload.

Steps to Reproduce:
-> Install opensearch-benchmark as mentioned in the [readme](https://github.com/opensearch-project/opensearch-benchmark/blob/main/README.md) file.
-> Run this command "opensearch-benchmark execute_test --distribution-version=1.0.0 --workload=http_logs".

Error:
->  "[ERROR] Cannot execute_test. Error in load generator [1]
	Cannot run task [index-append]: expected str, bytes or os.PathLike object, not NoneType"

All other workloads except http_logs are working fine.
