### ISSUE TITLE
Remove mapping types

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/opensearch-benchmark#150]
As part of v2.0 release, `mapping types` are getting removed from OpenSearch engine. Below are the changes in the opensearch-engine.
- Removal of type from rest end-points
- Removal of include_type_name parameter from API requests.

As part of this issue, please verify if type removal change on OpenSearch engine impacts this repository. If yes, then please remove the type references/usage from this repository

Related: [OpenSearch-engine meta issue](https://github.com/opensearch-project/opensearch/issues/1940)

**Comment by engechas** [comment]
This change will affect OSB, we will need to prioritize a fix.

### Areas of Change
https://github.com/opensearch-project/opensearch-benchmark/blob/bd88b91c5a38aa3fd328c087189ca944ad0d7714/osbenchmark/metrics.py#L80
https://github.com/opensearch-project/opensearch-benchmark/blob/f640f98cca7df30c1399262d8f26dcdd28ac6547/osbenchmark/resources/test-executions-template.json#L12
https://github.com/opensearch-project/opensearch-benchmark/blob/f640f98cca7df30c1399262d8f26dcdd28ac6547/osbenchmark/resources/metrics-template.json#L12
https://github.com/opensearch-project/opensearch-benchmark/blob/f640f98cca7df30c1399262d8f26dcdd28ac6547/osbenchmark/resources/results-template.json#L12

### Potential other areas that will need to change (needs further investigation)
https://github.com/opensearch-project/opensearch-benchmark/blob/bd88b91c5a38aa3fd328c087189ca944ad0d7714/tests/metrics_test.py#L376
https://github.com/opensearch-project/opensearch-benchmark/blob/bd88b91c5a38aa3fd328c087189ca944ad0d7714/tests/worker_coordinator/runner_test.py#L429
https://github.com/opensearch-project/opensearch-benchmark/blob/bd88b91c5a38aa3fd328c087189ca944ad0d7714/tests/worker_coordinator/runner_test.py#L447
https://github.com/opensearch-project/opensearch-benchmark/blob/bd88b91c5a38aa3fd328c087189ca944ad0d7714/osbenchmark/metrics.py#L777
https://github.com/opensearch-project/opensearch-benchmark/blob/bd88b91c5a38aa3fd328c087189ca944ad0d7714/osbenchmark/metrics.py#L1464
https://github.com/opensearch-project/opensearch-benchmark/blob/ad608cc3c0f1c3ea77d65bd780dc7b56fd6efc41/tests/workload/loader_test.py#L1991
https://github.com/opensearch-project/opensearch-benchmark/blob/ad608cc3c0f1c3ea77d65bd780dc7b56fd6efc41/tests/workload/loader_test.py#L2027
https://github.com/opensearch-project/opensearch-benchmark/blob/bd88b91c5a38aa3fd328c087189ca944ad0d7714/osbenchmark/worker_coordinator/runner.py#L919
https://github.com/opensearch-project/opensearch-benchmark/blob/ad608cc3c0f1c3ea77d65bd780dc7b56fd6efc41/tests/workload/params_test.py#L2247

The workloads may require changes as well. The "6" branch has [instances of doc in the index mappings](https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/6/eventdata/index.json#L8)
