### ISSUE TITLE
SigV4 support in OpenSearch Benchmark

### ISSUE THREAD

**Issue by achitojha** [opensearch-project/opensearch-benchmark#158]
**Is your feature request related to a problem? Please describe.**
Build SigV4 support into OpenSearch Benchmark to enable performance testing on clusters with SigV4 authentication mechanism

**Describe the solution you'd like**
Client options to be extended to enable sigV4 as another auth mechanism

**Comment by IanHoang** [comment]
Open PR for this feature: https://github.com/opensearch-project/opensearch-benchmark/pull/329

Currently in testing

**Comment by IanHoang** [comment]
Merged in https://github.com/opensearch-project/opensearch-benchmark/pull/329
