### ISSUE TITLE
Add AWS Signature support in opensearch-benchmark client

### ISSUE THREAD

**Issue by edzmh96** [opensearch-project/opensearch-benchmark#189]
**Is your feature request related to a problem? Please describe.**
Add AWS Signature support in opensearch-benchmark
**Describe the solution you'd like**
I'd like support for AWS Signature by default in opensearch-benchmark, instead of having to pipe requests through a reverse proxy like https://github.com/abutaha/aws-es-proxy

**Describe alternatives you've considered**
Running requests through a local proxy that signs the ES requests

**Additional context**

**Comment by IanHoang** [comment]
Duplicate of #158
