### ISSUE TITLE
Document usage of the execute_test command

### ISSUE THREAD

**Issue by travisbenedict** [opensearch-project/opensearch-benchmark#197]
**Is your feature request related to a problem? Please describe.**

There is no documentation on how to execute a test.

**Describe the solution you'd like**

Documentation for the `execute_test` command.

**Comment by IanHoang** [comment]
OpenSearch Benchmark 1.0.0 debuted with [documentation for executing tests](https://opensearch.org/docs/latest/benchmark/commands/execute-test/). Closing this issue
