### ISSUE TITLE
[BUG] what should be in the opensearch-benchmark-provisionconfigs ? 

### ISSUE THREAD

**Issue by HugoKuo** [opensearch-project/opensearch-benchmark#201]
Not seeing any document about this step. 

`
[benchmark@swiftsre002 ~]$ opensearch-benchmark execute_test --distribution-version=2.0.0 --workload=geonames --test-mode

   ____                  _____                      __       ____                  __                         __
  / __ \____  ___  ____ / ___/___  ____ ___________/ /_     / __ )___  ____  _____/ /_  ____ ___  ____ ______/ /__
 / / / / __ \/ _ \/ __ \\__ \/ _ \/ __ `/ ___/ ___/ __ \   / __  / _ \/ __ \/ ___/ __ \/ __ `__ \/ __ `/ ___/ //_/
/ /_/ / /_/ /  __/ / / /__/ /  __/ /_/ / /  / /__/ / / /  / /_/ /  __/ / / / /__/ / / / / / / / / /_/ / /  / ,<
\____/ .___/\___/_/ /_/____/\___/\__,_/_/   \___/_/ /_/  /_____/\___/_/ /_/\___/_/ /_/_/ /_/ /_/\__,_/_/  /_/|_|
    /_/

[ERROR] Cannot execute_test. Error in builder ([Errno 2] No such file or directory: '/home/benchmark/opensearch-benchmark-provisionconfigs')

Getting further help:
*********************
* Check the log files in /home/benchmark/.benchmark/logs for errors.
* Read the documentation at https://opensearch.org/docs.
* Ask a question on the forum at https://discuss.opendistrocommunity.dev/.
* Raise an issue at https://github.com/opensearch-project/OpenSearch-Benchmark/issues and include the log files in /home/benchmark/.benchmark/logs.

-------------------------------
[INFO] FAILURE (took 5 seconds)
-------------------------------
[benchmark@swiftsre002 ~]$ mkdir opensearch-benchmark-provisionconfigs
[benchmark@swiftsre002 ~]$ opensearch-benchmark execute_test --distribution-version=2.0.0 --workload=geonames --test-mode

   ____                  _____                      __       ____                  __                         __
  / __ \____  ___  ____ / ___/___  ____ ___________/ /_     / __ )___  ____  _____/ /_  ____ ___  ____ ______/ /__
 / / / / __ \/ _ \/ __ \\__ \/ _ \/ __ `/ ___/ ___/ __ \   / __  / _ \/ __ \/ ___/ __ \/ __ `__ \/ __ `/ ___/ //_/
/ /_/ / /_/ /  __/ / / /__/ /  __/ /_/ / /  / /__/ / / /  / /_/ /  __/ / / / /__/ / / / / / / / / /_/ / /  / ,<
\____/ .___/\___/_/ /_/____/\___/\__,_/_/   \___/_/ /_/  /_____/\___/_/ /_/\___/_/ /_/_/ /_/ /_/\__,_/_/  /_/|_|
    /_/

[ERROR] Cannot execute_test. Error in builder (Distribution version is less than available ES versions for provision-configs.)

Getting further help:
*********************
* Check the log files in /home/benchmark/.benchmark/logs for errors.
* Read the documentation at https://opensearch.org/docs.
* Ask a question on the forum at https://discuss.opendistrocommunity.dev/.
* Raise an issue at https://github.com/opensearch-project/OpenSearch-Benchmark/issues and include the log files in /home/benchmark/.benchmark/logs.

-------------------------------
[INFO] FAILURE (took 5 seconds)
-------------------------------
`

**Comment by travisbenedict** [comment]
Hey @HugoKuo thanks for your interest in OpenSearch Benchmark. I believe this is the same issue as https://github.com/opensearch-project/opensearch-benchmark/issues/106 which should be fixed with https://github.com/opensearch-project/opensearch-benchmark/pull/187. 

The next version release of OpenSearch Benchmark will have the fix.
