### ISSUE TITLE
OpenSearch benchmark support for Plugins/Extensions

### ISSUE THREAD

**Issue by vibrantvarun** [opensearch-project/opensearch-benchmark#208]
**Is your feature request related to a problem? Please describe.**

Use-case: We need to perform performance testing on OpenSearch with Extensions as well as Plugins running with it. To achieve that we need OpenSearch benchmark to be able to benchmark performance of plugins as well as extensions. Currently, the OpenSearch benchmark provides the benchmarking of OpenSearch cluster with operations defined in OpenSearch like create index, delete index etc.  Our requirement would be to add additional rest points which would be triggered from either extension or plugin.

Our use-case requires benchmark to also have a glance on performance of its extensions and plugins. 
@achitojha @IanHoang

**Comment by navneet1v** [comment]
+1 to this issue

**Comment by IanHoang** [comment]
We should draw the line on what should be added as a basic operation. Users can add custom operations within workloads. See example from the VectorSearch workload: https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/main/vectorsearch/runners.py

We have documentation coming out on how to do this soon. Feel free to reopen if needed.
