### ISSUE TITLE
OSB is not compatible with Shenandoah GC | Java 17

### ISSUE THREAD

**Issue by ayushav12** [opensearch-project/opensearch-benchmark#242]
**Describe the bug**
I created an OpenSearch-2.3 domain with updated JVM settings to use single-generation **Shenandoah Garbage Collector**. Then, to test my domain for performance, I setup OSB and ran **nyc_taxis** workload. The test run failed giving error : 

> in jvm_stats
>  old_gen_collection_time = gc["old"]["collection_time_in_millis"]
> 
> KeyError: 'old'
> 

 
Since, Shenandoah is single-generation GC, there's no concept on old-generation, new-generation and permanent-generation as in generic garbage collector algorithms.

**More Context (please complete the following information):**
- Workload(Share link for custom workloads) : nyc_taxis
- Service(E.g OpenSearch) : OpenSearch
- Version (E.g. 1.0) : 2.3

**Comment by IanHoang** [comment]
After taking a quick glance in the codebase, this is correct, OSB so far only supports multi-generational garbage collectors (like G1GC and CMS) and does not support experimental types of Garbage Collectors like Shenandoah. We'd have to look at incorporating support for single-generation GCs.

Although it's unlikely that you won't be needing it, if you still want to run node-stats on OS 2.3 without GC metrics, this can be done by running with additional parameters `--telemetry-params=node-stats-include-gc=false` in the OSB command.

**Comment by IanHoang** [comment]
This issue is similar to #206 and should be regarded as an enhancement rather than a bug because OSB currently supports GCs with concepts of old / young generations like G1GC and CMS GCs. We've currently implemented a short-term fix but will work on a long-term fix eventually.

**Comment by IanHoang** [comment]
No plans for adding support for Shenandoah GC for now
