### ISSUE TITLE
Provide a capability to increase the data corpus size for a workload

### ISSUE THREAD

**Issue by gkamat** [opensearch-project/opensearch-benchmark#254]
The data corpora supplied with the included workloads are generally small, under ~75 GB.  They do not suffice for performance testing larger clusters, scale testing and longevity testing.

Since acquiring larger data sets is not straightforward, it would be helpful to be able to provide some mechanism to increase the  corpus size for a workload.  This could be done through duplicating (and appropriately modifying) the existing documents in the corpus or by synthesizing documents.

**Comment by dblock** [comment]
Is this a dup/subset of https://github.com/opensearch-project/opensearch-benchmark/issues/253?

**Comment by gkamat** [comment]
This capability is [now available](https://github.com/opensearch-project/opensearch-benchmark/pull/273) for the `http_logs` workload There are several enhancements possible, including modifying the documents and regenerating queries, adding a similar capability to the other workloads, etc., but those will be addressed in dedicated issues that will be opened separately.

Closing this one.
