### ISSUE TITLE
Rename parameters for Distributed Workload Generation 

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#258]
**Is your feature request related to a problem? Please describe.**
### Background:
In some cases, users may find that a single host running OSB is not enough to generate traffic on a large cluster. This happens when the host running OSB maxes out its resources (CPU for example) during the test. Distributed Workload Generation is an OSB feature that prevents this situation by allowing users to use 3+ hosts to generate traffic on a cluster.

### How to Run Distributed Workload Generation
To use Distributed Workload Generation, users have to first start the **opensearch-benchmark daemon** on all hosts they plan to distribute load from. One of the hosts -- currently referred to as the **load coordinator host** -- coordinates requests while the others -- currently referred to as load worker coordinators hosts -- will drive the requests / load. For example, if we have three hosts -- denoted by IP1, IP2, and IP3 --, we would do run the corresponding command on each host:
```
# Run on IP1 Host
opensearch-benchmarkd start --node-ip=<IP1> --coordinator-ip=<IP1>
# Run on IP2 Host
opensearch-benchmarkd start --node-ip=<IP2> --coordinator-ip=<IP1>
# Run on IP3 Host
opensearch-benchmarkd start --node-ip=<IP3> --coordinator-ip=<IP1>
```

Once all the hosts have had the daemon successfully start on them, run the following command on the host we designated as `--coordinator-ip` in the commands above (in this case, IP1):
```
# Run test command on IP1 Host
opensearch-benchmark execute_test --pipeline=benchmark-only --workload=<workload> --load-worker-coordinator-hosts=<IP2,IP3> --target-hosts=<endpoint>
```
This starts the test. IP1 is the coordinator and delegates a portion of ingestion and search requests for IP2 and IP3 to send to the target cluster.

**Describe the solution you'd like**
### Improve terminology
Similar to how it was suggested to update `execute_test`(see issue #238), we should update the terminology used in Distributed Workload Generation. These terms could be slimmed down to **load-worker-hosts**, **worker-hosts**, or even **worker-ips** to be consistent with `--node-ip` and `--coordinator-ip`.  In the documentation, we should just refer to the hosts as **coordinator** and **workers**.  This renaming would make it less convoluted. 

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by IanHoang** [comment]
Will implement this after 1.0.0 release

**Comment by dosa-chammandi** [comment]
Hi @IanHoang ,
I would like to work on this.

**Comment by soumyatanwar** [comment]
Hi @dosa-chammandi - are you still working on this? If not, I could take this up. 
Let me know if you need help or would like to discuss this?

**Comment by dosa-chammandi** [comment]
> Hi @dosa-chammandi - are you still working on this? If not, I could take this up. Let me know if you need help or would like to discuss this?

Hi @soumyatanwar Thank you for the response. Yes I'm on it. I did the initial setup by setting up the dockers and openbenchmark. I faced some issues while setting up but its all cleared now. I'll try to finish this issue today. Can I ping you on slack for the queries?
