### ISSUE TITLE
OSB supporting ZSTD and ZSTDNODICT Compression Codecs

### ISSUE THREAD

**Issue by mulugetam** [opensearch-project/opensearch-benchmark#306]
**Describe the bug**
OSB, starting version 0.50, validates `index.codec` for valid compression codec values -- currently `default` and `best_compression`. But since version 2.7.0, OpenSearch also supports `ZSTD` and `ZSTDNODICT` compression codecs that OSB does not currently support. 

**To Reproduce**
```
opensearch-benchmark execute_test \
--workload=geonames \
--workload-params='{"index_settings":{"index.codec": "ZSTD"}}' \
--target-hosts=127.0.0.1:9200 \
--kill-running-processes \
--pipeline=benchmark-only \
--include-tasks=delete-index,create-index,index-append \
--kill-running-processes
```

**Expected behavior**
Must not throw a `invalid index.codec value 'ZSTD'` but it does. No errors should be thrown for `ZSTD` and `ZSTDNODICT` values for `index.codec` (and their lower-case equivalent: `zstd` and `zstdnodict`).

**More Context (please complete the following information):**
- OpenSearch 2.7.0
- OpenSearch Benchmark 0.5.0

**Comment by IanHoang** [comment]
Removing bug flag as this is an enhancement rather than a bug
