### ISSUE TITLE
Rename provision_config_instances

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#310]
**Is your feature request related to a problem? Please describe.**
`provision_config_instances` is a lot for users to type out and it doesn't offer much insight into what it is. We should also remove the underscore to streamline efforts to migrate to using hyphens instead of underscores.

**Describe the solution you'd like**

Since `provision_config_instances` are just configurations of clusters that can be provisioned by OpenSearch Benchmark, let's rename it to something more concise. Candidates so far are: "cluster-config".

**Describe alternatives you've considered**

**Additional context**

**Comment by cgchinmay** [comment]
Hi @IanHoang would like to work on this issue

**Comment by cgchinmay** [comment]
@IanHoang based on this [readme](https://github.com/opensearch-project/opensearch-benchmark/blob/main/docs/api/execute-test.md#all-arguments) so the suggestion is to update only the below command ?

`opensearch-benchmark list provision_config_instances`

while rest of these provisioning args can remain the same ?

- provision-config-path
- provision-config-repository
- provision-config-revision
- provision-config-instance
- provision-config-instance-params

**Comment by cgchinmay** [comment]
> @IanHoang based on this [readme](https://github.com/opensearch-project/opensearch-benchmark/blob/main/docs/api/execute-test.md#all-arguments) so the suggestion is to update only the below command ?
> 
> `opensearch-benchmark list provision_config_instances`
> 
> while rest of these provisioning args can remain the same ?
> 
> * provision-config-path
> * provision-config-repository
> * provision-config-revision
> * provision-config-instance
> * provision-config-instance-params

based on our slack discussion, will be updating the other args accordingly as well
