### ISSUE TITLE
Set default pipeline to benchmark-only

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#326]
**Is your feature request related to a problem? Please describe.**

A good majority of users use OSB to benchmark pre-existing clusters. 

**Describe the solution you'd like**

We should set the default to use benchmark-only pipeline.

**Describe alternatives you've considered**

**Additional context**

**Comment by cgchinmay** [comment]
@IanHoang Would like to work on this issue
