### ISSUE TITLE
Renaming the Indexing Codec from ZSTDNODICT to ZSTD_NO_DICT

### ISSUE THREAD

**Issue by sarthakaggarwal97** [opensearch-project/opensearch-benchmark#335]
**Is your feature request related to a problem? Please describe.**
There is an incoming [PR](https://github.com/opensearch-project/OpenSearch/pull/7908) in the OpenSearch, where we will be renaming the ZSTDNODICT codec to ZSTD_NO_DICT. This is being done to follow the best practices. When the PR for OpenSearch goes in, then there will be subsequent effects in the downstream OSB as well.

**Describe the solution you'd like**
Rename the codec to ZSTD_NO_DICT from the current ZSTDNODICT over [here](https://github.com/opensearch-project/opensearch-benchmark/blob/40ed4613f3faa353a08b0418befcb1e907366041/tests/workload/params_test.py#L1663) and [here](https://github.com/opensearch-project/opensearch-benchmark/blob/40ed4613f3faa353a08b0418befcb1e907366041/osbenchmark/workload/workload.py#L721)

**Comment by IanHoang** [comment]
Merged in the change
