### ISSUE TITLE
Print Real-Time Errors in Console during Test

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#349]
**Is your feature request related to a problem? Please describe.**

Many times, users realize their test had an error after their test has finished running and see a high error rate in the summary report. This is because OSB only presents the progress for each task/operation during the test but doesn't show real-time errors that OSB encounters.

**Describe the solution you'd like**

It'd be good to have issues presented in the console so that users can see real-time errors OSB encounters rather than seeing them in the logs or after the test finishes. 

**Describe alternatives you've considered**

**Additional context**

**Comment by cgchinmay** [comment]
would like to work on this issue @IanHoang
