### ISSUE TITLE
[Refactor] Rename put-pipeline to create-ingest-pipeline

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/opensearch-benchmark#366]
We enabled [the creation of search pipelines](https://github.com/opensearch-project/opensearch-benchmark/pull/364.) in opensearch-benchmark with the introduction of search pipelines in OS 2.9.0. To separate from the search pipeline, the ingest pipeline API put-pipeline should be refactored.

**Comment by Dantochi** [comment]
Hey, I would like to work on the first task which is: Refactor put-pipeline https://github.com/opensearch-project/opensearch-benchmark/issues/366...

**Comment by IanHoang** [comment]
@Dantochi if you'd like to contribute to this issue, please setup an OpenSearch Benchmark in Developer Mode. You can [see the Developer Guide] (https://github.com/opensearch-project/OpenSearch-Benchmark/blob/main/DEVELOPER_GUIDE.md) for reference.

**Comment by maddox05** [comment]
Hi! Saw the slack message and am ready to work on it.
