### ISSUE TITLE
Create-Workload Improvements: Write test_procedures and operations to individual directories and files.

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#376]
**Is your feature request related to a problem? Please describe.**

Currently, `create-workload` writes basic operations and customer provided operations to the workload.json. The workload.json that gets produced is the most basic workload form. The official workloads on the other hand use directories that house test_procedures and operations. This makes it more organized and extendable.

**Describe the solution you'd like**

`create-workload` should produce workloads with structures similar to the official workloads (have directories for test_procedures and operations instead of having everything in workload.json). This will streamline a "best practice" workload structure. 
 
**Describe alternatives you've considered**

**Additional context**

**Comment by AkshathRaghav** [comment]
Hi, I'd like to get started with this!

**Comment by AkshathRaghav** [comment]
Hi @IanHoang, I've made a PR on this issue. Will continue to work on it.
