### ISSUE TITLE
[CVE RISK] Upgrade urllib3 to v1.26.5

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#378]
### The Issue
An issue was discovered in urllib3, when provided with a URL containing many @ characters in the authority component, the authority regular expression exhibits catastrophic backtracking, causing a denial of service if a URL were passed as a parameter or redirected to via an HTTP redirect.

An issue was discovered in urllib3 before 1.26.5. When provided with a URL containing many @ characters in the authority component, the authority regular expression exhibits catastrophic backtracking, causing a denial of service if a URL were passed as a parameter or redirected to via an HTTP redirect.

### How to Fix 
The following branches contain urllib3 v1.25.11 and need to be upgraded to v1.26.5 or later.
- origin/main
- origin/1
- origin/1.1

**Comment by AkshathRaghav** [comment]
From my understanding, setup.py in the opensearch-benchmark branches install opensearch-py (different versions) which have "urllib3>=1.21.1" in install_requires. 

Should I add "urllib3>=1.26.5" in 'install_requires' of opensearch-py or opensearch-benchmark?

**Comment by maddox05** [comment]
As I see it opensearch-py requires urllib3 and downloads it, @AkshathRaghav, I think doing either would work. I think adding urllib3>=1.26.5 on setup.py (depending on how it's installed) should then update it to >1.26.5. Although I think adding it in OpenSearch-py would be the better option.

**Comment by IanHoang** [comment]
@AkshathRaghav Either would work as @maddox05 mentioned. Feel free to make a PR request to `opensearch-py` to see if they'd be willing to bump urllib3 from v1.21.1 to v1.26.5
- [opensearch-py's setup.py file](https://github.com/opensearch-project/opensearch-py/blob/main/setup.py#L53)

If they provide a reason why they cannot, we can opt to add `urllib3>=1.26.5` to our own setup.py

**Comment by maddox05** [comment]
@IanHoang will do, I'll keep you updated here.

**Comment by AkshathRaghav** [comment]
Pull request to the main branch - https://github.com/opensearch-project/opensearch-py/pull/515

Waiting for the checks to pass before I do the PRs for the other version branches in opensearch-py (which branch 1 and 1.1 here depend on)

**Comment by maddox05** [comment]
@AkshathRaghav possibly hardcoding it in 
- origin/main
- origin/1
- origin/1.1
wouldn't hurt.

**Comment by AkshathRaghav** [comment]
Sure that'd be easier tbh. But when setting it up, it'd install twice.

**Comment by maddox05** [comment]
it should be installed through opensearch library with the first command, and then if its already installed it should just skip it. Just as a backup in case opensearch-py library installed the wrong ver of urllib3.

**Comment by AkshathRaghav** [comment]
If the main opensearch-py setup has a dependency as 1.26.5, it can't install the wrong version; our setup.py will only install it if the module wasn't existing.

**Comment by maddox05** [comment]
that is what I meant yes sorry for the confusion.

**Comment by wbeckler** [comment]
Why not bump the opensearch-py version once https://github.com/opensearch-project/opensearch-benchmark/issues/378 happens?

**Comment by IanHoang** [comment]
@wbeckler our setup.py's `install_requires` doesn't specify urllib3 as a dependency since it is installed with opensearch-py. Instead of explicitly specifying it, it'll be more straightforward for OSB to to use the urllib3 that comes packaged with`opensearch-py`.

Note: https://github.com/opensearch-project/opensearch-py/pull/518 has been merged in

**Comment by AkshathRaghav** [comment]
Will do @IanHoang 👍
