### ISSUE TITLE
Ability to redirect the execute_test output to file

### ISSUE THREAD

**Issue by ansjcy** [opensearch-project/opensearch-benchmark#379]
**Is your feature request related to a problem? Please describe.**
Currently, because of the sys.stdout.isatty() check in https://github.com/opensearch-project/opensearch-benchmark/blob/main/osbenchmark/utils/console.py#L157, there's no way to do redirect for the execution output.

**Describe the solution you'd like**
We want to support opensearch-benchmark to output to stdout even when it is not connected to a terminal, such as when a shell redirection is employed. 

**Describe alternatives you've considered**

**Additional context**

**Comment by IanHoang** [comment]
@ansjcy Have you tried appending the parameter `--results-file`? This parameter tells OSB to write the command line output to the specified file.

**Comment by IanHoang** [comment]
Closing issue as this feature is supported already. Please feel free to reopen if needed.
