### ISSUE TITLE
[BUG] Remove generate subcommand

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#384]
**Describe the bug**
We should deprecate the generate_chart command as this is not used extensively by users and currently does not work. Dashboards should be a central tool to build charts out of OSB metrics. 

**To Reproduce**
When users run `opensearch-benchmark generate --chart-type="time-series"` from the documentation, the following error is revealed on the console:
```
opensearch-benchmark generate: error: the following arguments are required: artifact, --chart-spec-path
```

**Comment by beaioun** [comment]
Hi @IanHoang I would like to work on this one.  I'll start digging the issue while anyone else with insights can also share in the comment. 😊
