### ISSUE TITLE
Add ZSTD Compression and Decompression Support for Corpora

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#385]
**Is your feature request related to a problem? Please describe.**

As of now, OSB compresses files with bzip2 (when creating workloads) and can decompress corpora with the following file extensions before running workloads:
- zip
- bzip2
- gz
- tar
- tar.gz
- tgz
- tar.bz2

We should also add support zstd compression and decompression for corpora. When compared to bzip2, ZSTD's compressed files are notably smaller in size. Compared to other decompression algorithms, ZSTD is very fast and takes less time to decompress. Giving users the option to decompress and compress large corpora quickly would be beneficial.

For more insight into compression algorithms, see: https://linuxreviews.org/Comparison_of_Compression_Algorithms#Notable_Takeaways

**Comment by beaioun** [comment]
Hi guys, I'll start to work on this issue and I am open to collaboration. Comment below or DM if you want to work together!

**Comment by beaioun** [comment]
Hey @IanHoang, As I was working with testing, I found that especially for nyc_taxis which has a size of over 70g, it takes a very long time to download and decompress before it can be worked on. I think we could add a zstd compressed version of workloads to the osb-workload repository, for a faster decompression rate.

**Comment by beaioun** [comment]
Hey @IanHoang as I was performing tests, I found that large workloads such as the nyc_taxis, which has a size of over 70g, take a very long time to download and decompress. Since we are now capable of decompressing zstd files, we could create zstd compressed version of the workloads in the workload repo for a faster decompression rate.

**Comment by IanHoang** [comment]
> Hey @IanHoang as I was performing tests, I found that large workloads such as the nyc_taxis, which has a size of over 70g, take a very long time to download and decompress. Since we are now capable of decompressing zstd files, we could create zstd compressed version of the workloads in the workload repo for a faster decompression rate.

@beaioun Thanks for the contribution here. This will be certainly useful. I'll add a good first issue in the workloads repository related to your comment.
