### ISSUE TITLE
[BUG] OSB does not respect git branching when running local workloads

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/opensearch-benchmark#401]
**Describe the bug**
I'm running the latest python instance of OSB. I also have OSB workloads repository where I have changed made in a particular branch. I'm using the `--workload-repository` flag to specify that OSB should use my local version of the workloads. When running OSB I get an error describing that the test procedure I am trying to run does not exist. After running the workload I see that OSB workloads now points to main rather than my branch.

**To Reproduce**
 - Use local version of OSB workloads and check into a new branch
 - Run OSB pointing to local version of OSB workloads
 - Check that OSB workloads switches from feature branch to main branch

**Expected behavior**
OSB to execute workload from feature branch rather than main.

**Logs**
```
opensearch-benchmark-workloads git:(pmc_prefix_queries) opensearch-benchmark execute-test --pipeline=benchmark-only --workload=pmc --target-host="xxx:80"  --workload-repository="/home/hvamsi/code/opensearch-benchmark-workloads" --kill-running-processes --test-procedure="append-and-prefix" --test-mode

   ____                  _____                      __       ____                  __                         __
  / __ \____  ___  ____ / ___/___  ____ ___________/ /_     / __ )___  ____  _____/ /_  ____ ___  ____ ______/ /__
 / / / / __ \/ _ \/ __ \\__ \/ _ \/ __ `/ ___/ ___/ __ \   / __  / _ \/ __ \/ ___/ __ \/ __ `__ \/ __ `/ ___/ //_/
/ /_/ / /_/ /  __/ / / /__/ /  __/ /_/ / /  / /__/ / / /  / /_/ /  __/ / / / /__/ / / / / / / / / /_/ / /  / ,<
\____/ .___/\___/_/ /_/____/\___/\__,_/_/   \___/_/ /_/  /_____/\___/_/ /_/\___/_/ /_/_/ /_/ /_/\__,_/_/  /_/|_|
    /_/

[ERROR] Cannot execute-test. Error in test execution orchestrator (Unknown test_procedure [append-and-prefix] for workload [pmc])

Getting further help:
*********************
* Check the log files in /home/hvamsi/.benchmark/logs for errors.
* Read the documentation at https://opensearch.org/docs.
* Ask a question on the forum at https://forum.opensearch.org/.
* Raise an issue at https://github.com/opensearch-project/OpenSearch-Benchmark/issues and include the log files in /home/hvamsi/.benchmark/logs.

-------------------------------
[INFO] FAILURE (took 0 seconds)
-------------------------------
➜  opensearch-benchmark-workloads git:(main) 
```

We can see that OSB workloads pointed to `pmc_prefix_queries` branch before running OSB and then to main after running.

**More Context (please complete the following information):**
- Workload(Share link for custom workloads)
- Service(E.g OpenSearch)
- Version (E.g. 1.0)

**Additional context**

**Comment by gkamat** [comment]
Looking into this issue.

**Comment by IanHoang** [comment]
@harshavamsi Is this still an issue? Seems like it's been some time and we are now on version 1.10. Feel free to reopen this issue if you're still experiencing this
