### ISSUE TITLE
[FEATURE]  Replace RequestsHttpConnection by Urllib3HttpConnection

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-benchmark#408]
**Describe the bug**

Looking at https://github.com/opensearch-project/opensearch-benchmark/blob/3adacc0a9383cf7f81dbe0cba4c4f6c0b206cab2/osbenchmark/client.py#L296 the code is using `RequestsHttpConnection`, which is much slower than the default `Urllib3HttpConnection `.

The reason is probably Sigv4 support, which was added to `Urllib3HttpConnection` in https://github.com/opensearch-project/opensearch-py/pull/547. Replace `RequestsHttpConnection` with `Urllib3HttpConnection`.

**Comment by rishabh6788** [comment]
Closing this issue as the PR has been merged.
