### ISSUE TITLE
Release 1.20 ( payload with vector search )

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-benchmark#428]
Once #103 is completed, we would like to have a new release to support runners and param sources that are added for  vector search workload.

**Comment by IanHoang** [comment]
1.2.0 release is scheduled for Jan

**Comment by gkamat** [comment]
The release is scheduled for the latter part of January.

**Comment by VijayanB** [comment]
@vamshin  This will be blocker for us to integrate nightly runs.

**Comment by VijayanB** [comment]
@gkamat Can you share expected release date? Thanks

**Comment by IanHoang** [comment]
@VijayanB We are expecting to release 1.2.0 by 1/18/2024.

**Comment by VijayanB** [comment]
1.2.0 is released. Please check [here](https://github.com/opensearch-project/opensearch-benchmark/releases/tag/1.2.0)
