### ISSUE TITLE
[BUG] [Need-Help]Timeout error while creating a custom workload

### ISSUE THREAD

**Issue by VinDataR** [opensearch-project/opensearch-benchmark#480]
We are trying to create a custom workload from a existing OpenSearch cluster using a below command; 

```
opensearch-benchmark create-workload \
--workload="sample-index" \
--target-hosts="opensearch-master:9200" \
--client-options="basic_auth_user:'****',basic_auth_password:'****'" \
--indices="sample-index-5" \
--output-path="/opensearch-benchmark/.benchmark" --offline 
```
This command is constantly ending in timeout error. Default timeout is mentioned as 10 seconds. We are not seeing an explicit flag to increase timeout from default 10s. Does anyone has any idea how to increase the timeout for create-workload command. Attached error screenshot.

![image (4)](https://github.com/opensearch-project/opensearch-benchmark/assets/163123878/06886729-7e1b-45a3-9394-dd7ca989aa52)

**Comment by IanHoang** [comment]
Hi @VinodRakuten, we currently have an [RFC](https://github.com/opensearch-project/opensearch-benchmark/issues/395) for enhancing the `create-workload` feature and mentions this issue and a proposed solution. We'll be implementing these enhancements soon. Feel free to comment on the RFC if you have any comments or questions.

### To better help you:
- What's the command you're running (Please redact any information from the command as we only want to check the flags that are being used)?
- How many indices are you running against?
- How large are these indices in terms of GB?
- What's the average size of the shards?

### Manual Work-around
For very large indices, one work-around that I've had successful experiences with is running the `create-workload` feature on indices independently. This will essentially create separate workloads and you'll have to combine the workload.jsons that are produced. For example, if I want to extract corpora from indices A, B, and C, I'd run the `create-workload` feature separately for each index. Afterwards, I'll have three different workloads -- one for A, one for B, and one for C -- and I'd create a new workload.json that combines elements from all three workloads' workload.json. 

This isn't ideal but it gets the job done. Some of these issues should be resolved once we enhance this feature in the future based on this [RFC](https://github.com/opensearch-project/opensearch-benchmark/issues/395) plan.

**Comment by VinDataR** [comment]
Thank you for your reponse @IanHoang.  We tried the manual workaround by merging the workload.json but it didn't work. Maybe we might missed some pieces while combining them. We'll give it another shot.

**Comment by IanHoang** [comment]
@VinDataR what were the errors that you encountered? Could you provide the exact steps you performed and the exception here? Feel free to redact any private information if sending screenshots or commands.

**Comment by VinDataR** [comment]
We were just getting this ReadTimeOut error while running the create-workload command in opensearch-benchmark.Below is the screenshot from the command.

![image](https://github.com/opensearch-project/opensearch-benchmark/assets/163123878/fb6583ce-2425-405c-b1e7-ccbe954eeeb8)

We were able to create the workload successfully with the method you had suggested.

**Comment by VinDataR** [comment]
One more query that might be different to the topic of this issue;(Please let me know if it requires raising a separate issue);

We are trying to create a 500GB size custom workload by running create-workload for multiple indices of 40GB size each and combining them all into a single workload.json. The challenge is that each create-workload command takes around 6-8 hours to complete. Is there any way we can speed this up?

Below is the command we are running;(replaced possible sensitive information with **** symbol )

```
nohup opensearch-benchmark create-workload \
--workload="*******" \
--target-hosts="*******" \
--client-options="basic_auth_user:'******',basic_auth_password:'******'" \
--indices="********" \
--output-path="/opensearch-benchmark/.benchmark/benchmarks" --offline &
```

**Comment by IanHoang** [comment]
@VinDataR We plan to work on a faster workaround for extracting corpora and give `create-workload` "restart" options, to pick up from where the timeout occurred. These can be found in the [RFC](https://github.com/opensearch-project/opensearch-benchmark/issues/395) I linked above.

**Comment by gkamat** [comment]
@IanHoang,  perhaps follow-up with @VinDataR to see if the updates to create-workload have fixed this issue.

**Comment by IanHoang** [comment]
@VinDataR Is this still an open issue? Feel free to reopen it if needed
