### ISSUE TITLE
[BUG] Add sleep interval into Jenkins workflow when publishing new OSB versions 

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#486]
**Describe the bug**
When Jenkins workflow is triggered, OSB first publishes to PyPI and then Dockerhub staging. Recently, we have discovered that the Dockerhub staging encounters this error:
```
#14 [linux/amd64 4/6] RUN if [ -z "1.4.0" ] ; then python3 -m pip install opensearch-benchmark ; else python3 -m pip install opensearch-benchmark==1.4.0 ; fi
#0 1.734 ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.8,<3.10; 0.0.2 Requires-Python >=3.8,<3.10; 0.1.0 Requires-Python >=3.8,<3.10
#0 1.735 ERROR: Could not find a version that satisfies the requirement opensearch-benchmark==1.4.0 (from versions: 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.3.1)
```
It's been tested and confirmed that this can be resolved if we add a sleep in the Jenkins workflow [script](https://github.com/opensearch-project/opensearch-benchmark/blob/main/jenkins/release.JenkinsFile).

**To Reproduce**
Trigger release

**Expected behavior**
This should not happen because PyPI already published the new version.

**Logs**
https://build.ci.opensearch.org/job/docker-build/4997/console

**More Context (please complete the following information):**
- Workload(Share link for custom workloads)
- Service(E.g OpenSearch)
- Version (E.g. 1.0)

**Additional context**

**Comment by gkamat** [comment]
Fixed with #635
