### ISSUE TITLE
[BUG] Can't use benchmark and jupyter notebook in the same python env as their dependency versions conflict

### ISSUE THREAD

**Issue by chishui** [opensearch-project/opensearch-benchmark#499]
**Describe the bug**
As described in this [feature request in OpenSearch](https://github.com/opensearch-project/OpenSearch/issues/13009), I'm writing a python script to call opensearch-benchmark with different parameters to see which parameter could lead to better ingestion performance. I also want to use jupyter notebook to visualize the parameters in the notebook and we can let user to run process step by step.

However, opensearch-benchmark has a very strict restriction on dependency version and most of the versions are stale https://github.com/opensearch-project/opensearch-benchmark/blob/main/setup.py#L58. So the version conflict with jupyter's dependency, for example, opensearch-benchmark needs `jsonschema==3.1.1`, but jupyter notebook needs `jsonschema>=4.18.0` ([code](https://github.com/jupyter/jupyter_events/blob/76433e74b22ce6e465699a4fbf3dc16965fa7183/pyproject.toml#L27))

**To Reproduce**
1. `pip install opensearch-benchmark`
2. `pip install notebook`
3. run `opensearch-benchmark`, will see error message:
```
Traceback (most recent call last):
  File "/Users/xiliyun/projects/opensearch-find-optimal/bin/opensearch-benchmark", line 5, in <module>
    from osbenchmark.benchmark import main
  File "/Users/xiliyun/projects/opensearch-find-optimal/lib/python3.11/site-packages/osbenchmark/__init__.py", line 31, in <module>
    __version__ = pkg_resources.require("opensearch-benchmark")[0].version
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiliyun/projects/opensearch-find-optimal/lib/python3.11/site-packages/pkg_resources/__init__.py", line 937, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiliyun/projects/opensearch-find-optimal/lib/python3.11/site-packages/pkg_resources/__init__.py", line 798, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/xiliyun/projects/opensearch-find-optimal/lib/python3.11/site-packages/pkg_resources/__init__.py", line 844, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (MarkupSafe 2.1.5 (/Users/xiliyun/projects/opensearch-find-optimal/lib/python3.11/site-packages), Requirement.parse('markupsafe==2.0.1'), {'opensearch-benchmark'})
```

**Expected behavior**
opensearch-benchmark can loosen the version requirement for its dependencies. Instead of using a fixed version, it can set a minimal supported version like "markupsafe>=2.0.1"

**Logs**
If applicable, add logs to help explain your problem.

**More Context (please complete the following information):**
- Workload(Share link for custom workloads)
- Service(E.g OpenSearch)
- Version (E.g. 1.0)

**Additional context**

**Comment by IanHoang** [comment]
Thanks for bringing this to our attention @chishui! We'll get a fix out for this when we get a chance. If you'd like, you can contribute this quick change and tag us in the PR when it's ready.
