### ISSUE TITLE
Support "request-params" for bulk operation

### ISSUE THREAD

**Issue by chishui** [opensearch-project/opensearch-benchmark#500]
**Is your feature request related to a problem? Please describe.**
[_bulk API supports multiple parameters](https://opensearch.org/docs/latest/api-reference/document-apis/bulk/) but only pipeline is supported in workload. User has no way to configure bulk operation in workload using other parameters. We need a general way to configure bulk parameters under "bulk" operation and they will be part of the bulk API parameters.

**Describe the solution you'd like**
Bulk operation supports "request-params" field which is key-value pairs. Example configuration is shown below:
```
{
      "operation": {
        "operation-type": "bulk",
        "bulk-size": {{bulk_size | default(5000)}},
        "ingest-percentage": {{ingest_percentage | default(100)}},
        "request-params": {
          "batch_ingestion_option": "enabled",
          "maximum_batch_size":{{batch_size}}
        }
      },
      "clients": {{bulk_indexing_clients | default(2)}}
    }
```
**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by IanHoang** [comment]
Merged in enhancement. Thanks for contributing @chishui!
