### ISSUE TITLE
Provide instructions on how to run without Docker Desktop

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/opensearch-benchmark#51]
**Is your feature request related to a problem? Please describe.**

In early 2022, [Docker Desktop will no longer be free to use](https://www.docker.com/blog/updating-product-subscriptions/). The development of Benchmarks seems to be tied to `docker-compose` as per the Developer Guide. Docker Desktop is used on Windows and MacOS to provide access to both the Docker Engine and Docker Compose. Meaning many potential developers will not be able to contribute.

**Describe the solution you'd like**

Link to resources and alter the developer guide to include alternate methods of developing Benchmarks without Docker Desktop ([example](https://dhwaneetbhatt.com/blog/run-docker-without-docker-desktop-on-macos)).

**Describe alternatives you've considered**

1. Move to Helm chart or similar
2. Change to non-containerized execution somehow.

**Comment by IanHoang** [comment]
Since OSB 0.2.0, we are not dependent on Docker Desktop. Closing this issue out.
