### ISSUE TITLE
Lock numpy version to be smaller than 2.0.0 due to h5py 3.11.0 adding support for numpy 2.0

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-benchmark#522]
Hi,

Lock numpy to be lower than 2.0.0 due to h5py 3.11.0 adding support for numpy 2.0.

H5py 3.11.0: https://github.com/h5py/h5py/pull/2405/files#diff-4e5ae07b2507dc64ddd4b9ea97a0ad9a666a883fcef637ff941a5d30aeb3f166

Numpy 2.0 rc: https://pypi.org/project/numpy/2.0.0rc1/

numpy not locked smaller than 2.0.0: https://github.com/opensearch-project/opensearch-benchmark/blob/1.5.0/setup.py#L109

Thanks.

**Comment by IanHoang** [comment]
Added lock here: https://github.com/opensearch-project/opensearch-benchmark/blob/main/setup.py#L109
