### ISSUE TITLE
[BUG] Error in Delete ML Model Runner

### ISSUE THREAD

**Issue by vpehkone** [opensearch-project/opensearch-benchmark#541]
**Describe the bug**
The deleting ML model can fail, if the undeploying model has not yet completed.

**To Reproduce**
Run DeleteMlModel runner, when there is already registered and deployed ML model.
Use workload to run it: Run the workload treccovid_semantic_search (this workload is not yet merged to main repo) two times. In the second run, the task delete-ml-model can fail.

**Expected behavior**
If there is already register and deployed model, it will be undeployed and deleted.

**More Context (please complete the following information):**
- Workload: https://github.com/vpehkone/opensearch-benchmark-workloads/tree/neural_search/treccovid_semantic_search

**Comment by IanHoang** [comment]
Closing as the fix is merged in
