### ISSUE TITLE
Permit large data corpora to be downloaded from the workloads repository

### ISSUE THREAD

**Issue by gkamat** [opensearch-project/opensearch-benchmark#543]
### Description
CloudFront limits restrict the size of data corpus files that can be downloaded to 50 GB.  Thus, in the case of the `big5` workload, for example, a corpus with an uncompressed size of 1 TB is currently not feasible, since the corresponding compressed size exceeds this limit.

It may be necessary to implement multipart downloads to work around this problem.  Other alternatives could also be investigated.

**Comment by getsaurabh02** [comment]
@gkamat can we share the approach for this?

**Comment by gkamat** [comment]
This focuses on enabling OSB to download large compressed data corpora as separate chunks.  Currently an index is associated with a single data corpus file and is restricted to the 50 GiB limit imposed by CloudFront.  Permitting workloads to be able to specify multiple files as comprising a single index will get around this limit.

This issue does not focus on download speed, per se.  Index download efficiency will be addressed as part of a separate issue, since it is a generally a one-time activity when running a workload, but the problem described above needs to be resolved to permit larger data corpora to be used at all.
