### ISSUE TITLE
[RFC]:  Scale-Up Improvements on Single Load Generation Host 

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#555]
### Synopsis

This RFC is intended to address OpenSearch Benchmark’s (OSB) limitations pertaining to operation at large scale.  Several users have reported that OSB performance tests do not scale when a large number of client threads is specified.  Overcoming this limitation is crucial for the OpenSearch community as it will unblock these users and other stakeholders and potentially lead to the development of new features within OpenSearch.  This RFC proposes an investigation into the scaling limitations and subsequent options to overcome them, which may include modifications to OSB’s client architecture.

### Motivation

By specifying certain workload parameters, OSB users can alter characteristics of a benchmark. OSB has a clients parameter that allows users to specify the number of parallel threads to perform a task or operation. This parameter can be specified by setting bulk_indexing_clients and search_clients; these simulate the number of clients that issue indexing and search requests respectively. By default, workloads packaged with OSB have bulk_indexing_clients set to 8 and search_clients set to 1 unless the user specifies otherwise. These clients all run in parallel on the load generation host where OSB is installed and invoked. OSB achieves this by leveraging the [Thespianpy library](https://thespianpy.com/doc/), an actor model framework.

When a user wants to increase the intensity of load imposed on the target system-under-test (an OpenSearch cluster or a Serverless implementation), the natural technique is to increase the number of clients by utilizing one of the parameters above.  By doing this, users can simulate the traffic patterns seen in their production environments and better understand their cluster’s limitations. 

However, many users have reported that OSB encounters scaling limitations when the number of clients is increased beyond a certain level.  Such bottlenecks may result from OSB’s client architecture design, such asthis one that details how OSB cannot scale out the number of clients or is unable to achieve certain throughput levels due to design constraints. Users have claimed they can scale up to 16 clients successfully but OSB performance begins to degrade once they go beyond 32 clients. There have also been reports that the current client architecture might not use the load generation host’s resources effectively. To combat these pain points, some users have  found makeshift ways to get around these limitations and discovered that such workarounds can lead to better resource utilization and workload performance.

Evidently, even a highly efficient application running on a single load generation host will cease to scale beyond a certain point, when the resources available are all consumed by the workload.  At that point, it will become necessary to scale-up by using a beefier instance, or to scale-out by adding additional load-generation hosts that operate in parallel.  With regard to the latter, Distributed Workload Generation (DWG) is a feature that comes with OSB and coordinates a group of load generation hosts to drive load to the OpenSearch cluster. This feature, that uses a scaled out number of hosts, is intended for use in the scenario described above. However, the feature has not been thoroughly tested and the exact scenarios of when it should be used is not well understood. 

This RFC was inspired by these user pain points and focuses on understanding which OSB components are involved in simulating clients, what the limitations are with these components, and which changes can be made to remove such limitations, thereby making the use of a single load generation host’s resources more efficient.  

There will be a separate RFC to address DWG. This RFC proposes that there will be two phases related to scale testing. The first phase will focus on making OSB scale as well as possible and the second focusing on DWG, which will have its own RFC. The first phase will consist of identifying limitations, verifying workarounds, tracking down bottlenecks or causes of the limitations, overcoming bottlenecks, and publishing info on discoveries and actions taken.

This RFC also provides opportunity in determining if OSB should support other language clients for OpenSearch. Since OSB is primarily based in Python, there have been questions on if the Python GIL, which is known to prevent parallelism, or Python’s Async IO library limits OSB’s scalability in search clients. If Python is a limitation, OSB might need to be rearchitected to become more modular and be able to use other OpenSearch language clients (such as Go, Rust, and Java).

### Areas of Interest

Since this RFC is focused enhancing OSB performance at scale, our areas of interest will be on the Worker Coordinator Actor and the Worker Actor(s) since they are primarily involved in scaling out clients which consume the load generation host’s resources. Specifically, we’re interested in analyzing the components’ code, stress testing them, and seeing how they perform under various conditions to identify any shortcomings. For more information on why we chose these areas of interest, see the Appendix. 

### Stakeholders

* OpenSearch users who want to test large data corpora and at high-load intensities and commercial serverless offerings of OpenSearch that are interested in simulating high-intensity loads to test their service’s efficacy in scaling out
* OpenSearch users and developers who want to simulate clients seen in their production environment or performance test new features
* Commercial managed services that track OpenSearch performance for the releases they offer against large clusters
* Corporate benchmarking teams, who may be interested in benchmarking their use-cases with OpenSearch against other options

### Proposed Priorities 

This RFC proposes a separation of associated activities into two sequential investigations:
  * The first will focus on the scaling aspects of OSB on a single load generation host.
  * The second will focus on DWG improvements in a distributed load generation deployment, and will have its own RFC.

Community engagement is invited and will help with both phases. Scale testing OSB’s client architecture will need to be thorough to ensure we are covering enough scope and feedback on this front will be helpful. More details for the first phase are explored in the following section. 

### Requirements

Investigating and improving OSB’s client architecture can be broken down into several steps:

1. **Identify current limits:** The OSB community is aware that there are limitations in terms of scaling clients within OSB, but is unsure of what those exact limitations are. A majority of the time, OSB is used as a single load generation host to emulate the performance of a fleet of nodes. Therefore, a performance comparison between a cluster of nodes, each with OSB set to a single client, and a single node with OSB set to several clients will help uncover what those exact limitations are. 
2. **Identify workarounds if possible:** After understanding the limitations, we will determine if there are any quick workarounds that users can resort to to alleviate scaling limitations, while work progresses on long-term solutions.
3. **Investigate bottlenecks (or causes of limitations):** For the limitations discovered in step 1, we will need to investigate the bottlenecks in more depth and identify causes.
4. **Overcome bottlenecks**: Identify and implement appropriate solutions on how to resolve bottlenecks and remove limitations 
5. **Publish info on discoveries and actions taken:** After all the work has been done, we should summarize our findings and solutions and ensure that OSB has been appropriately updated to handle scaling better.
 
Subsequent issues will be created to address these requirements and elaborate on implementation details.

### Use Cases

* As an OpenSearch user and developer, I want to be able to accurately simulate the number of clients I anticipate to see or have seen in my production environment
* As an OpenSearch user, I would like to test large workloads at high intensities
* As an OpenSearch user, I would like to have reliable metrics when simulating clients
* As an OpenSearch user and developer, I want to be able to scale out the number of clients or have OSB auto-scale its clients to reach a specific throughput levels
* As an OpenSearch developer, I would like to perform scale tests to determine how my OpenSearch cluster performs at various scales

### How Can You Help?

* Any general comments about the overall direction are welcome.
* Indicating whether the areas identified above for investigating and improving OSB’s client architecture and performance include your scenarios and use-cases will be helpful in prioritizing them.
* Provide early feedback when analyzing results from the investigation and testing out new features to enhance OSB’s client architecture as soon as they become available.
* Help out on the implementation! Check out the [issues page](https://github.com/opensearch-project/opensearch-benchmark/issues) for work that is ready to be picked up.

### Next Steps

We will incorporate feedback and add more details on design, implementation and prototypes as they become available.

#### Benchmarking Process Under the Hood
OSB uses a group of actors that are based on the thespian.actors from Thespianpy library, an actor model framework available in Python. These actors coordinate with one another and can be viewed as the components that make up OSB’s benchmarking process.

Each actor has its own responsibility. For example, the Benchmark Actor starts the overall benchmarking process and calls upon the Builder Actor to determine if there is a provisioned OpenSearch cluster. The Worker Coordinator Actor is called upon to prepare the benchmark by communicating with the Workload Preparation Actor. To supply load to the OpenSearch cluster, the Worker Coordinator Actor provisions a number of Worker Actors based on the number of CPU cores in the load generation host. Based on the number of clients (such as bulk_indexing_clients and search_clients) set in the workload or specified by the user, Worker Actors will be allocated a number of clients and steps (also known as tasks or operations in workloads) to execute. These workers will split up the work and each simulate N number of clients. Once the workers and their respective clients have finished executing a step, they will reconvene at a joinpoint before the Worker Coordinator Actor informs them to proceed to the next step.

**Comment by gkamat** [comment]
This is a timely RFC.  Understanding how well OSB scales is essential to carrying out accurate and meaningful performance tests.  A few comments:
  * This investigation should not be restricted to search clients.  Ingestion is just as important a phase and for implementations like Serverless, ingestion rate is an important factor in determining when to scale out the compute resources.
  * Milestones should be moved out of the RFC into child tasks.  The meta issue for this project should be noted at the beginning of the RFC for easy reference.
  * Effort and duration should be tracked separately, since schedules can change and there may be multiple participants working on this effort.  A general high-level estimate should suffice, even in the child tasks, rather than precise dates.
  * The ASG strategy for comparison is a good technique.  It will help to lay out an overview of the _modus operandi_ in the synopsis, rather than in the description of the experiments.
  * Would it make sense to use OSB with a single client on each ASG node rather than using an `opensearch-py` client?  This may be helpful for ingestion and perhaps even for queries, rather than setting up the tooling for a script and an ingestion corpus.
  * With regard to worker actors, there is also the question of the right number of actors per core.  Perhaps more than 1 actor may result in better utilization and improved scaling.  This is an area that deserves some attention.

**Comment by IanHoang** [comment]
I have updated the RFC to be more high-level and concise based on the feedback received.

**Comment by IanHoang** [comment]
## Questions We Had

Based on various stakeholder experiences, a few questions we aim to answer are:

1. Does OSB accurately simulate clients in a client-server model? If it’s inaccurately simulating clients, then this would mean that it is unable to scale properly. 
2. To what throughput level can OSB scale up on a single load generation host of a specified instance type?
3. At the scaling limit, which system resource is the one that is the primary cause of the limit? Is this related to one of the software modules used in OSB, such as Thespian, Asyncio, etc.?

## Our findings from the OSB team from last year: 

Based on the experiments conducted, OSB scaled properly on a single load generation host and there were even cases where throughput limits were encountered on the server side. In summary, we have made the following conclusions:

### OSB accurately simulates clients in a client-server model

To illustrate what we mean by “accurately simulates clients in a client-server model”, imagine there are two setups. The first setup includes 25 EC2 instances, where each instance has OSB using a single thread to drive load to a cluster. In the other setup, there is instead only a single EC2 instance that has OSB using 25 threads to drive load to a cluster. After running tests and comparing results between both setups, we found that the throughput and latencies were similar. We repeated this test with various number of instances and CPU cores and the results remained consistent.

### More powerful instance types permit higher throughput

The more CPU cores in a single load generation host, the higher the throughput OSB can achieve. We observed the following when running a term query against a 20 node cluster with c5.4xlarge data nodes:

* A single m5d.8xlarge with OSB using 5000 threads can achieve up to 7200 ops/s 
* A single m5d.16xlarge with OSB using 5000 threads can achieve up to 15,000 ops/s. In this case, target cluster CPU reached 70%.

Based on our results, users can boost throughput as long as the load generation host has enough CPU cores. It’s also recommended that the user choose the load generation host based on the size of the cluster and the cluster’s data node type.

### More instances permit higher throughput

Although Distributed Workload Generation (DWG) was not used, doubling the load generation hosts doubled the throughput as long as the server side (cluster) was not the bottleneck. At this time, we observed that the following can be achieved when running a term query against a 20 node cluster with c5.4xlarge data nodes:

* Two m5d.16xlarges, each with OSB using 5000 threads, can drive up to 20,000 ops/s (each host can drive up to 10,000 ops/s). This setup saturated target cluster CPU, making it reach 92%. 

### A bug exists but does not hinder performance

Based on the tests conducted, we identified that there is a bug in OSB. When users use more than 4000+ threads (or search clients), OSB does not generate a summary report at the end of the test. However, OSB still completes the benchmark and achieves the desired throughput levels, and can therefore scale beyond 4000 threads still. To give an example, when using 4500 threads on a m5d.8xlarge (32 vCPUs) instance, we were able to achieve the expected throughput according to CloudWatch metrics on the server side but the summary report was never generated.

It’s been confirmed that this isn’t an issue with the load generation host’s resources but rather an implementation issue within OSB. Regardless of the size of the load generation host, the issue still happens when using more than 4500 threads. 

There are suspicions that this implementation issue is related to modules used in OSB. Some speculations are that Thespianpy might be unable to manage the synchronization of 4000+ threads at the join-point or that there are potential issues in the AsyncIO implementations we inherited at the fork. However, no conclusion can be made until we further investigate this.

An issue has been created for this issue #633
