### ISSUE TITLE
[META] Enhance OpenSearch Benchmark Documentation

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#611]
The [OSB documentation](https://opensearch.org/docs/latest/benchmark/) [debuted in 2023](https://github.com/opensearch-project/opensearch-benchmark/issues/101#issuecomment-1577258540) and has been improved on over the course of the last year. As new users join the community and OSB continues to grow, the documentation should be continuously refined. This META issue is dedicated to making enhancements towards the documentation.

Below is a table of planned enhancements to the documentation:
| Page Title / Task                       | Which Section to Add in | PRs | Status      |
|-----------------------------------------|-------------------------|-----|-------------|
| OSB 2.0.0 & Migration Steps             | User Guide & Reference  |   https://github.com/opensearch-project/documentation-website/pull/7888  | Doc-Review   |
| Enhance Operations Reference            | User Guide & Reference  |  https://github.com/opensearch-project/documentation-website/pull/7974/files   | Doc-Review |
| Glossary                                | Reference               |     | In Progress|
| Flesh out Telemetry Devices in User Guide                                | Reference               |     | Not Started |
| Reorganize User Guide into Sub Sections                                | Reference               |     | Not Started |
| Build Custom Components                 | Tutorials              |     | Not Started |
| Create Workload Enhancements            | User Guide              |     | Not Started |
| Performance Testing Best Practices      | User Guide              |     | Not Started |
| How to Duplicate the Nightly Runs Setup | Tutorials               |     | Not Started |
| Enhance Developer Documentation         | User Guide              |     | Not Started |
| Tutorial: Setup OSB in a VPC / non-VPC  | Tutorials               |     | Not Started |

**Comment by Naarcha-AWS** [comment]
Enhance Operations Reference is In-Progress. We'll start the Glossary this week as well.

**Comment by IanHoang** [comment]
OSB 2.0.0 document has been reviewed and will be converted to a draft until we are ready to release OSB 2.0.0

**Comment by IanHoang** [comment]
Let's convert this to a board and convert them items into issues

**Comment by IanHoang** [comment]
Deprecating this as we can now use the board https://github.com/orgs/opensearch-project/projects/228/views/1
