### ISSUE TITLE
[META] Introduce Aggregate Command

### ISSUE THREAD

**Issue by OVI3D0** [opensearch-project/opensearch-benchmark#628]
META issue for issues related to this RFC: #627

Issues based off priorities from RFC:
* Add Ability to aggregate results across multiple OSB test executions: #629 
* Enhance Compare command to be able to compare aggregated results from two or more test executions: #630 
* Incorporate automatic aggregation into new and existing features: #631 
* Store Aggregated results in a separate local folder #661 
* Add relative standard deviation (RSD) to the new aggregate feature #662 
* Add support for custom iteration values #670 
* Add median values and adjust min/max values #684

**Comment by IanHoang** [comment]
@OVI3D0 Can you create a few more tasks and add them to this META issue?
- Support storing results in MDS https://github.com/opensearch-project/opensearch-benchmark/pull/638#discussion_r1764063130
- Store aggregations in separate local folder (such as `~/.benchmark/benchmarks/aggregations`)  https://github.com/opensearch-project/opensearch-benchmark/pull/638#discussion_r1764063130
- Add RSD to aggregation test execution JSON https://github.com/opensearch-project/opensearch-benchmark/pull/655#issuecomment-2379910316
