### ISSUE TITLE
Add short-hand alternatives for commonly-used command line options

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#639]
### Is your feature request related to a problem? Please describe

OSB has a few command-line options that offer short hand alternatives. An example is the following, added by @peteralfonsi .
```
    test_execution_parser.add_argument(
        "--randomization-repeat-frequency",
        "-rf",
        help=f"The repeat_frequency for query randomization. Ignored if randomization is off"
             f"(default: {workload.loader.QueryRandomizerWorkloadProcessor.DEFAULT_RF}).",
        default=workload.loader.QueryRandomizerWorkloadProcessor.DEFAULT_RF)
```

This improves the user experience and removes the dread of typing out long command-line options.

### Describe the solution you'd like

We should include short hand alternatives for the following commonly-used options for each subcommand:

### execute-test 
- [ ] `--workload`
- [ ] `--target-hosts`
- [ ] `--client-options`
- [ ] `--workload-params`
- [ ] `--test-execution-id`
- [ ] `--kill-running-processes`

### compare

- [ ] `--baseline`
- [ ] `--contender`

### create-workload

- [ ] `--workload`
- [ ] `--indices`
- [ ] `--target-hosts`
- [ ] `--client-options`

By only focusing on the commonly-used options, we will avoid polluting OSB's namespace with convoluted short flags while also improving the user experience. If an option that's added in the future becomes commonly-used, we can add a short flag then.

If there are other commonly-used options that I missed, please feel free to comment them below.

**Comment by OVI3D0** [comment]
Hey @IanHoang I can take this issue!
