### ISSUE TITLE
Automated trigger for Integration tests

### ISSUE THREAD

**Issue by achitojha** [opensearch-project/opensearch-benchmark#87]
**Is your feature request related to a problem? Please describe.**
OpenSearch Benchmark has automated way to run unit tests, however, no such support exists for integration tests. The goal of this issue is to build an automated trigger to run integration tests.

**Describe the solution you'd like**
[This script](https://github.com/opensearch-project/opensearch-benchmark/blob/main/.ci/build.sh#L54) is currently used to run unit tests on every pull request. We can extend the same to provide support for integration tests.

Reference : Instruction on running integration tests can be found [here](https://github.com/opensearch-project/opensearch-benchmark/blob/main/DEVELOPER_GUIDE.md#executing-tests).

**Describe alternatives you've considered**
- Create automation using a separate jenkins infrastructure

**Comment by travisbenedict** [comment]
Closed with https://github.com/opensearch-project/opensearch-benchmark/pull/130
