### ISSUE TITLE
Support performance tests for OpenSearch Cross Cluster Replication 

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/opensearch-benchmark#88]
**Is your feature request related to a problem? Please describe.**
We want to use opensearch benchmark for triggering performance tests for cross cluster replication. This issue is to track the changes required. 

**Describe the solution you'd like**

- Support using a telemetry device which can read the cross cluster replication status and log into the metric store: [
Status API](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/replication.html#replication-confirm)
- Support passing multiple endpoints using Opensearch-benchmark.

**Additional context**
- Since opensearch-benchmark is a fork of Elasticsearch's rally, it already has support for CCR on elasticsearch. 
- Ex: https://www.elastic.co/blog/benchmarking-elasticsearch-cross-cluster-replication
- Telemetry device: https://github.com/opensearch-project/opensearch-benchmark/blob/main/osbenchmark/telemetry.py#L317
- Rally recipe: https://github.com/elastic/rally/blob/master/recipes/ccr/start.sh

**Comment by travisbenedict** [comment]
https://github.com/opensearch-project/opensearch-benchmark/pull/104 closes this
