### ISSUE TITLE
[BUG] Corrupt benchmark data

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/opensearch-benchmark#90]
**Describe the bug**
I followed https://github.com/opensearch-project/OpenSearch-Benchmark/blob/main/DEVELOPER_GUIDE.md to run the benchmark on `Amazon Linux Developer Desktop` and it failed with following error (logs attached):

```
[ERROR] Cannot execute_test. Error in task executor
	Download of [/home/ankikala/.benchmark/benchmarks/data/eventdata/eventdata.json.bz2] is corrupt. Downloaded [1159168] bytes but [792768300] bytes are expected. Please retry.
```

**To Reproduce**
- Checkout opensearch-benchmark.
- Setup all the prereq in Developer Guide linked above.
- execute `make prereq` 
- execute `make install`
- `source .venv/bin/activate`
- Run the benchmark test. sample command: ```opensearch-benchmark execute_test --workload=eventdata --target-hosts=endpoint --pipeline=benchmark-only --workload-params="number_of_replicas:1" --client-options="use_ssl:true,basic_auth_user:USERNAME,basic_auth_password:PASSWORD,verify_certs:false" --kill-running-processes```

**Expected behavior**
Benchmark test should execute successfully.

**Logs**
[log-devdesktop.txt](https://github.com/opensearch-project/opensearch-benchmark/files/7717121/log-devdesktop.txt)

 ```
Traceback (most recent call last):

  File "/home/ankikala/.pyenv/versions/3.8.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)

  File "/local/home/ankikala/ws/opensearch-benchmark/osbenchmark/workload/loader.py", line 418, in prepare_docs
    preparator.prepare_document_set(document_set, data_root[0])

  File "/local/home/ankikala/ws/opensearch-benchmark/osbenchmark/workload/loader.py", line 575, in prepare_document_set
    self.downloader.download(document_set.base_url, target_path, expected_size)

  File "/local/home/ankikala/ws/opensearch-benchmark/osbenchmark/workload/loader.py", line 490, in download
    net.download(data_url, target_path, size_in_bytes, progress_indicator=progress)

  File "/local/home/ankikala/ws/opensearch-benchmark/osbenchmark/utils/net.py", line 239, in download
    raise exceptions.DataError("Download of [%s] is corrupt. Downloaded [%d] bytes but [%d] bytes are expected. Please retry." %

osbenchmark.exceptions.DataError: Download of [/home/ankikala/.benchmark/benchmarks/data/eventdata/eventdata.json.bz2] is corrupt. Downloaded [1159168] bytes but [792768300] bytes are expected. Please retry.```

**Comment by travisbenedict** [comment]
Are you able to run a test using a different workload? I received the same error when trying `eventdata`, but I did a quick check and was able to use the `geonames` and `percolator` workloads.

I'll look into the data corruption issue. We may have missed something when uploading the dataset for `eventdata`

**Comment by ankitkala** [comment]
Thanks. I was able to run other workloads just fine.

**Comment by achitojha** [comment]
Hi Ankit,

You should be able to run eventdata as well now.
