### ISSUE TITLE
Plugin Framework

### ISSUE THREAD

**Issue by achitojha** [opensearch-project/opensearch-benchmark#98]
Enable OpenSearch Benchmark to be extensible by having a plugin framework - this framework should allow the following : 

* Developers should be able to write their own plugins for specific features like load generator instance provisioning, cluster provisioning, publishing reports to data store, formatting reports in specific formats, etc
* There should be a plugin registry which would allow developers to register plugins

**Comment by gkamat** [comment]
Closing in favor of more specifically targeted issues.
